---

- name: Import konsave profile
  ansible.builtin.command: "konsave -i {{playbook_dir}}/assets/{{konsave['name']}}.knsv"

- name: Apply konsave profile
  ansible.builtin.command: "konsave -a {{ konsave['name'] }}"

- name: Quit plasmashell
  ansible.builtin.shell: "kquitapp6 plasmashell && sleep 6"

- name: Reload plasmashell
  ansible.builtin.shell: "kstart plasmashell && sleep 5"
#
#- name: Change wallpaper
#  ansible.builtin.command: "plasma-apply-wallpaperimage {{ wallpaper }}"
#
