---

- name: Import konsave profile
  ansible.builtin.command: "konsave -i {{ konsave['profile'] }}"

- name: Apply konsave profile
  ansible.builtin.command: "konsave -a {{ konsave['name'] }}"

- name: Change wallpaper
  ansible.builtin.command: "plasma-apply-wallpaperimage {{ wallpaper }}"

