---
- name: AUR package preparation
  ansible.builtin.import_tasks: aur.yml

- name: Install nix packages using curl
  ansible.builtin.import_tasks: nix.yml

- name: Install packages
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  become: true


- name: Install packages from AUR
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    state: present
    use: auto
  become: true
  become_user: aur_builder


