---
- name: Install packages using curl
  ansible.builtin.import_tasks: nix.yml

- name: Install dev packages
  community.general.pacman:
    name: "{{ dev_packages }}"
    state: present
    executable: yay
    extra_args: --noconfirm
  become: true

- name: Install other packages
  community.general.pacman:
    name: "{{ sys_packages }}"
    state: present
    executable: yay
    extra_args: --noconfirm
  become: true
